// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// initialize_python
void initialize_python();
RcppExport SEXP spacyr_initialize_python() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    initialize_python();
    return R_NilValue;
END_RCPP
}
// finalize_python
void finalize_python();
RcppExport SEXP spacyr_finalize_python() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    finalize_python();
    return R_NilValue;
END_RCPP
}
// pycall
void pycall(std::string command);
RcppExport SEXP spacyr_pycall(SEXP commandSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type command(commandSEXP);
    pycall(command);
    return R_NilValue;
END_RCPP
}
