# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_python <- function() {
    invisible(.Call('spacyr_initialize_python', PACKAGE = 'spacyr'))
}

finalize_python <- function() {
    invisible(.Call('spacyr_finalize_python', PACKAGE = 'spacyr'))
}

pycall <- function(command) {
    invisible(.Call('spacyr_pycall', PACKAGE = 'spacyr', command))
}

